server:
  port: ${multiplecloudservices.port}
  error:
    include-stacktrace: never

spring:
  application:
    name: multiple-cloud-services
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${multiplecloudservices.datasource.url}
    username: ${multiplecloudservices.datasource.username}
    password: ${multiplecloudservices.datasource.password}
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    baseline-on-migrate: true